compatibility_flags = [ "nodejs_compat_v2" ]
pages_build_output_dir = './dist'
name = 'astro-clerk-cloudflare'
compatibility_date = '2024-09-02'

[vars]
PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_dHJ1c3Rpbmcta2l0ZS0zNy5jbGVyay5hY2NvdW50cy5kZXYk"
CLERK_SECRET_KEY = "sk_test_CMWH8RJIOSMUbWLSrrxfxx5NYQHj3fq6QjQELYH39t"
PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL= "/protected"
PUBLIC_CLERK_SIGN_IN_URL="/sign-in"
PUBLIC_CLERK_SIGN_UP_URL="/sign-up"